---
dist: trusty
sudo: false

env:
  matrix:
    - TERRAFORM_VERSION: 0.11.13

language: python
python: 3.6
cache:
  pip: true
  directories:
    - tool/eggs

script: make docs test

notifications:
  email:
    on_success: never
    on_failure: never
